### PR TITLE
Fixed a trucate problem with the seq rename

### LINKED ISSUE #325: Create a table in Builder fails
Seems to be related to the fix introduced by @pramsey [here](https://github.com/CartoDB/cartodb-postgresql/pull/319)

The error is:

```
PG::Error: ERROR:  CDB(_CDB_Rewrite_Table:42P07:relation "wadus_table_c22d5412_2cf2_11e8_bfd3_00163ef2a37a_cartodb_id_seq" already exists): ALTER SEQUENCE public.wadus_table_c22d5412_2cf2_11e8_bfd3_00163ef2a37a_cartodb_id_seq RENAME
 TO wadus_table_c22d5412_2cf2_11e8_bfd3_00163ef2a37a_cartodb_id_seq_tmp
CONTEXT:  PL/pgSQL function _cdb_sql(text,text) line 9 at RAISE
SQL statement "SELECT _CDB_SQL(Format('ALTER SEQUENCE %s RENAME TO %s_tmp', relseq, destseq), '_CDB_Rewrite_Table')"
PL/pgSQL function _cdb_rewrite_table(regclass,text) line 126 at PERFORM
SQL statement "SELECT _CDB_Rewrite_Table(reloid, destschema)"
PL/pgSQL function cdb_cartodbfytable(text,regclass) line 51 at PERFORM: 
          SELECT cartodb.CDB_CartodbfyTable('public'::TEXT,'public.wadus_table_c22d5412_2cf2_11e8_bfd3_00163ef2a37a'::REGCLASS);    
```

And you can reproduce opening a rails console and doing:

```
u = Carto::User.find_by_username('{{username}}')
table = Table.new
table.user_id = u.id
table.name = 'wadus_table_' + UUIDTools::UUID.timestamp_create.to_s
table.save
```

### PR DESCRIPTION
**Pull request by ethervoid**
Closes #325

### CODE REVIEW

**Comment by ethervoid** [comment]
Second round @jgoizueta , cartodb branch is :green_apple:

File: scripts-available/CDB_CartodbfyTable.sql [hunk 1]
```diff
@@ -906,12 +906,12 @@ BEGIN
   -- so we check to see if that's the case, and rename it out of the way
   IF has_usable_primary_key AND has_usable_pk_sequence THEN
     -- See if the existing sequence is squatting on our preferred name
-    destseq := Format('%s_%s_seq', relname, const.pkey);
+    destseq := Format('tmp_%s_%s_seq', relname, const.pkey);
```
Comment (jgoizueta) [inline scripts-available/CDB_CartodbfyTable.sql]: But now you're checking if the `tmp_*` seq exists (see comparison with relseq below). This seems wrong to me.
